<?php echo $this->partial('partial/base/form/password-reset', array('form' => $this->form, 'success' => $this->success, 'error' => $this->error)); ?>
<div class="create-account">
    <p>Nie masz konta ?&nbsp; <a href="javascript:;" id="register-btn">Stwórz konto</a></p>
</div>
<?php echo $this->partial('partial/base/form/registration', array('form' => $this->registrationForm)); ?>

<script>
    var loginPageUrl = '<?php echo $this->url('login');?>';
</script>