<?php

namespace DoctrineMigrations;

use Doctrine\DBAL\Migrations\AbstractMigration;
use Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
class Version20160313215724 extends AbstractMigration
{
    /**
     * @param Schema $schema
     */
    public function up(Schema $schema)
    {
        $this->addSql
        ("
			INSERT INTO `country` (`code`, `name`, `date_create`)
			VALUES
                ('AF', 'Afganistan', NOW()),
                ('AL', 'Albania', NOW()),
                ('DZ', 'Algieria', NOW()),
                ('AS', 'Samoa Amerykańskie', NOW()),
                ('AD', 'Andorra', NOW()),
                ('AO', 'Angola', NOW()),
                ('AI', 'Anguilla', NOW()),
                ('AR', 'Argentyna', NOW()),
                ('AM', 'Armenia', NOW()),
                ('AW', 'Aruba', NOW()),
                ('AU', 'Australia', NOW()),
                ('AT', 'Austria', NOW()),
                ('AZ', 'Azerbejdżan', NOW()),
                ('BS', 'Bahamas', NOW()),
                ('BH', 'Bahrajn', NOW()),
                ('BD', 'Bangladesz', NOW()),
                ('BB', 'Barbados', NOW()),
                ('BY', 'Białoruś', NOW()),
                ('BE', 'Belgia', NOW()),
                ('BZ', 'Belize', NOW()),
                ('BJ', 'Benin', NOW()),
                ('BM', 'Bermudy', NOW()),
                ('BT', 'Bhutan', NOW()),
                ('BO', 'Boliwia', NOW()),
                ('BA', 'Bośnia i Hercegowina', NOW()),
                ('BW', 'Botswany', NOW()),
                ('BV', 'Bouvet Wyspa', NOW()),
                ('BR', 'Brazylia', NOW()),
                ('IO', 'Brytyjskie Terytorium Oceanu Indyjskiego', NOW()),
                ('BN', 'Brunei Darussalam', NOW()),
                ('BG', 'Bułgaria', NOW()),
                ('BF', 'Burkina Faso', NOW()),
                ('BI', 'Burundi', NOW()),
                ('KH', 'Kambodża', NOW()),
                ('CM', 'Kamerun', NOW()),
                ('CA', 'Kanada', NOW()),
                ('CV', 'Wyspy Zielonego Przylądka', NOW()),
                ('KY', 'Kajmany', NOW()),
                ('CF', 'Republika Środkowoafrykańska', NOW()),
                ('TD', 'Czad', NOW()),
                ('CL', 'Chile', NOW()),
                ('CN', 'Chiny', NOW()),
                ('CX', 'Wyspa Bożego Narodzenia', NOW()),
                ('CC', 'Cocos (Keeling) Islands', NOW()),
                ('CO', 'Kolumbia', NOW()),
                ('KM', 'Komory', NOW()),
                ('CG', 'Kongo', NOW()),
                ('CD', 'Kongo, Republika Demokratyczna', NOW()),
                ('CK', 'Wyspy Cooka', NOW()),
                ('CR', 'Kostaryka', NOW()),
                ('CI', 'Wybrzeże Kości Słoniowej', NOW()),
                ('HR', 'Chorwacja (Hrvatska)', NOW()),
                ('CU', 'Kuba', NOW()),
                ('CY', 'Cypr', NOW()),
                ('CZ', 'Republika Czeska', NOW()),
                ('DK', 'Dania', NOW()),
                ('DJ', 'Dżibuti', NOW()),
                ('DM', 'Dominika', NOW()),
                ('DO', 'Republika Dominikany', NOW()),
                ('EC', 'Ekwador', NOW()),
                ('EG', 'Egipt', NOW()),
                ('SV', 'Salwador', NOW()),
                ('GQ', 'Gwinea Równikowa', NOW()),
                ('ER', 'Erytrea', NOW()),
                ('EE', 'Estonia', NOW()),
                ('ET', 'Etiopia', NOW()),
                ('FK', 'Falklandy (Malwiny)', NOW()),
                ('FO', 'Wyspy Owcze', NOW()),
                ('FJ', 'Fidżi', NOW()),
                ('FI', 'Finlandia', NOW()),
                ('FR', 'Francja', NOW()),
                ('GF', 'Gujana Francuska', NOW()),
                ('PF', 'Polinezja Francuska', NOW()),
                ('TF', 'Francuskie Terytoria Południowe', NOW()),
                ('GA', 'Gabon', NOW()),
                ('GM', 'Gambii', NOW()),
                ('GE', 'Gruzja', NOW()),
                ('DE', 'Niemcy', NOW()),
                ('GH', 'Ghana', NOW()),
                ('GI', 'Gibraltar', NOW()),
                ('GR', 'Grecja', NOW()),
                ('GL', 'Greenland', NOW()),
                ('GD', 'Grenada', NOW()),
                ('GP', 'Gwadelupa', NOW()),
                ('GU', 'Guam', NOW()),
                ('GT', 'Gwatemala', NOW()),
                ('GN', 'Gwinea', NOW()),
                ('GW', 'Gwinea Bissau', NOW()),
                ('GY', 'Gujana', NOW()),
                ('HT', 'Haiti', NOW()),
                ('HM', 'Wyspy Heard i Mc Donald', NOW()),
                ('VA', 'Stolica Apostolska (Państwo Watykańskie)', NOW()),
                ('HN', 'Honduras', NOW()),
                ('HK', 'Hongkong', NOW()),
                ('HU', 'Węgry', NOW()),
                ('IS', 'Islandia', NOW()),
                ('IN', 'Indie', NOW()),
                ('ID', 'Indonezja', NOW()),
                ('IR', 'Iran (Islamska Republika)', NOW()),
                ('IQ', 'Irak', NOW()),
                ('IE', 'Irlandia', NOW()),
                ('IL', 'Izrael', NOW()),
                ('IT', 'Włochy', NOW()),
                ('JM', 'Jamaica', NOW()),
                ('JP', 'Japonia', NOW()),
                ('JO', 'Jordania', NOW()),
                ('KZ', 'Kazachstan', NOW()),
                ('KE', 'Kenia', NOW()),
                ('KI', 'Kiribati', NOW()),
                ('KP', 'Republika Korei Ludowo-Demokratyczna', NOW()),
                ('KR', 'Republika Korei', NOW()),
                ('KW', 'Kuwejt', NOW()),
                ('KG', 'Kirgistan', NOW()),
                ('LA', 'Laotańska Republika Ludowo-Demokratyczna', NOW()),
                ('LV', 'Łotwa', NOW()),
                ('LB', 'Liban', NOW()),
                ('LS', 'Lesoto', NOW()),
                ('LR', 'Liberia', NOW()),
                ('LY', 'Libia', NOW()),
                ('LI', 'Liechtenstein', NOW()),
                ('LT', 'Litwa', NOW()),
                ('LU', 'Luksemburg', NOW()),
                ('MO', 'Macau', NOW()),
                ('MK', 'Macedonia, Była Jugosłowiańska Republika', NOW()),
                ('MG', 'Madagaskar', NOW()),
                ('MW', 'Malawi', NOW()),
                ('MY', 'Malezja', NOW()),
                ('MV', 'Malediwy', NOW()),
                ('ML', 'Mali', NOW()),
                ('MT', 'Malta', NOW()),
                ('MH', 'Wyspy Marshalla', NOW()),
                ('MQ', 'Martynika', NOW()),
                ('MR', 'Mauretania', NOW()),
                ('MU', 'Mauritius', NOW()),
                ('YT', 'Majotta', NOW()),
                ('MX', 'Meksyk', NOW()),
                ('FM', 'Mikronezja, Sfederowane Stany', NOW()),
                ('MD', 'Mołdawia, Republika', NOW()),
                ('MC', 'Monaco', NOW()),
                ('MN', 'Mongolia', NOW()),
                ('MS', 'Montserrat', NOW()),
                ('MA', 'Maroko', NOW()),
                ('MZ', 'Mozambik', NOW()),
                ('MM', 'Myanmar', NOW()),
                ('NA', 'Namibia', NOW()),
                ('NR', 'Nauru', NOW()),
                ('NP', 'Nepal', NOW()),
                ('NL', 'Holandia', NOW()),
                ('AN', 'Antyle Holenderskie', NOW()),
                ('NC', 'Nowa Kaledonia', NOW()),
                ('NZ', 'Nowa Zelandia', NOW()),
                ('NI', 'Nikaragua', NOW()),
                ('NE', 'Niger', NOW()),
                ('NG', 'Nigeria', NOW()),
                ('NU', 'Niue', NOW()),
                ('NF', 'Wyspa Norfolk', NOW()),
                ('MP', 'Mariany Północne', NOW()),
                ('NO', 'Norwegia', NOW()),
                ('OM', 'Oman', NOW()),
                ('PK', 'Pakistan', NOW()),
                ('PW', 'Palau', NOW()),
                ('PA', 'Panama', NOW()),
                ('PG', 'Papua Nowa Gwinea', NOW()),
                ('PY', 'Paragwaj', NOW()),
                ('PE', 'Peru', NOW()),
                ('PH', 'Filipiny', NOW()),
                ('PN', 'Pitcairn', NOW()),
                ('PL', 'Polska', NOW()),
                ('PT', 'Portugalia', NOW()),
                ('PR', 'Portoryko', NOW()),
                ('QA', 'Katar', NOW()),
                ('RE', 'Reunion', NOW()),
                ('RO', 'Rumunia', NOW()),
                ('RU', 'Federacja Rosyjska', NOW()),
                ('RW', 'Rwandy', NOW()),
                ('KN', 'Saint Kitts i Nevis', NOW()),
                ('LC', 'saint Lucia', NOW()),
                ('VC', 'Saint Vincent i Grenadyny', NOW()),
                ('WS', 'Samoa', NOW()),
                ('SM', 'San Marino', NOW()),
                ('ST', 'Sao Tome i Principe', NOW()),
                ('SA', 'Arabia Saudyjska', NOW()),
                ('SN', 'Senegal', NOW()),
                ('SC', 'Seszele', NOW()),
                ('SL', 'Sierra Leone', NOW()),
                ('SG', 'Singapur', NOW()),
                ('SK', 'Słowacja (Republika Słowacka)', NOW()),
                ('SI', 'Słowenia', NOW()),
                ('SB', 'Wyspy Salomona', NOW()),
                ('SO', 'Somali', NOW()),
                ('ZA', 'Afryka Południowa', NOW()),
                ('GS', 'Georgia Południowa i Sandwich Południowy', NOW()),
                ('ES', 'Hiszpania', NOW()),
                ('LK', 'Sri Lanka', NOW()),
                ('SH', 'Helena', NOW()),
                ('PM', 'Saint-Pierre i Miquelon', NOW()),
                ('SD', 'Sudan', NOW()),
                ('SR', 'Surinam', NOW()),
                ('SJ', 'Svalbard i Jan Mayen', NOW()),
                ('SZ', 'Suazi', NOW()),
                ('SE', 'Szwecja', NOW()),
                ('CH', 'Szwajcaria', NOW()),
                ('SY', 'Republika Syryjsko-Arabska', NOW()),
                ('TW', 'Tajwan, Prowincja Chin', NOW()),
                ('TJ', 'Tadżykistan', NOW()),
                ('TZ', 'Tanzania, Zjednoczona Republika', NOW()),
                ('TH', 'Tajlandia', NOW()),
                ('TG', 'Iść', NOW()),
                ('TK', 'Tokelau', NOW()),
                ('TO', 'Tonga', NOW()),
                ('TT', 'Trynidad i Tobago', NOW()),
                ('TN', 'Tunezja', NOW()),
                ('TR', 'indyk', NOW()),
                ('TM', 'Turkmenia', NOW()),
                ('TC', 'Wyspy Turks i Caicos', NOW()),
                ('TV', 'Tuvalu', NOW()),
                ('UG', 'Uganda', NOW()),
                ('UA', 'Ukraina', NOW()),
                ('AE', 'Zjednoczone Emiraty Arabskie', NOW()),
                ('GB', 'Zjednoczone Królestwo', NOW()),
                ('US', 'Stany Zjednoczone', NOW()),
                ('UM', 'Stany Zjednoczone Dalekie Wyspy Mniejsze', NOW()),
                ('UY', 'Urugwaj', NOW()),
                ('UZ', 'Uzbekistan', NOW()),
                ('VU', 'Vanuatu', NOW()),
                ('VE', 'Wenezuela', NOW()),
                ('VN', 'Wietnam', NOW()),
                ('VG', 'Wyspy Dziewicze (Brytyjskie)', NOW()),
                ('VI', 'Wyspy Dziewicze (USA)', NOW()),
                ('WF', 'Wallis i Futuna', NOW()),
                ('EH', 'Sahara Zachodnia', NOW()),
                ('YE', 'Jemen', NOW()),
                ('ZM', 'Zambia', NOW()),
                ('ZW', 'Zimbabwe', NOW());
        ");
    }

    /**
     * @param Schema $schema
     */
    public function down(Schema $schema)
    {
        $this->addSql
        ("
			DELETE FROM `country`;
        	ALTER TABLE `country` AUTO_INCREMENT = 1;
		");
    }
}
