<?php
/**
 * Configuration file generated by ZFTool
 * The previous configuration file is stored in application.config.old
 *
 * @see https://github.com/zendframework/ZFTool
 */

$applicationEnv = getenv('APPLICATION_ENV') ?: 'production';

return array(
    'modules' => array(
        'DoctrineModule',
        'DoctrineORMModule',
        'EdpModuleLayouts',
        'base',
        'user'
    ),
    'module_listener_options' => array(
        'module_paths' => array(
            './module',
            './vendor',
        ),
        'config_glob_paths' => array(
        	sprintf('config/autoload/{,*.}{global,local,%s}.php', $applicationEnv),
        ),
    ),
);
