<div class="no-display modal fade" id="addAppointmentModal" role="dialog" aria-labelledby="addAppointmentModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                <h4 class="modal-title">Dodaj nową wizytę</h4>
            </div>
            <div class="modal-body margin-bottom-40">
                <?php echo $this->partial('partial/user/form/appointment', array('form' => $this->form)); ?>
            </div>
            <div class="modal-footer">
                <button id="addAppointmentSubmitBtn" class="btn btn-success" type="button"><i class="fa fa-check"></i> Zapisz</button>
                <button data-dismiss="modal" class="btn btn-default" type="button">Anuluj</button>
            </div>
        </div>
    </div>
</div>