<?php
$form = $this->form;
$form->prepare();
echo $this->form()->openTag($form);
?>
<h3 class="form-title">Zaloguj się</h3>
<div id="loginErrorAlert" class="alert alert-danger display-hide">
    <button class="close" data-close="alert"></button>
    <span></span>
</div>
<div class="form-group <?php if($this->formElementErrors($form->get('email'))) echo "has-error has-feedback" ?>">
    <label class="control-label visible-ie8 visible-ie9"><?php echo $form->get('email')->getLabel(); ?></label>
    <div class="input-icon">
        <i class="fa fa-user"></i>
        <?php echo $this->formElement($form->get('email'));?>
        <?php if($this->formElementErrors($form->get('email'))) : ?>
            <span class="help-inline"><?php echo $this->formElementErrors($form->get('email')) ?></span>
        <?php endif; ?>
    </div>
</div>
<div class="form-group <?php if($this->formElementErrors($form->get('password'))) echo "has-error has-feedback" ?>">
    <label class="control-label visible-ie8 visible-ie9"><?php echo $form->get('password')->getLabel(); ?></label>
    <div class="input-icon">
        <i class="fa fa-lock"></i>
        <?php echo $this->formElement($form->get('password'));?>
        <?php if($this->formElementErrors($form->get('password'))) : ?>
            <span class="help-inline"><?php echo $this->formElementErrors($form->get('password')) ?></span>
        <?php endif; ?>
    </div>
</div>
<div class="form-actions">
    <label class="checkbox"><?php echo $this->formElement($form->get('rememberMe'));?> <?php echo $form->get('rememberMe')->getLabel(); ?></label>
    <button id="loginFormSubmitBtn" class="btn blue pull-right">Zaloguj <i class="m-icon-swapright m-icon-white"></i></button>
</div>
<?php echo $this->form()->closeTag($form); ?>