<?php
$form = $this->form;
$form->prepare();
echo $this->form()->openTag($form);
?>
<h3>Zapomniałeś hasła ?</h3>
<p>Wprowadź swój adres email, aby przypomnieć hasło</p>
<div id="passwordRecoverySuccessAlert" class="alert alert-success display-hide">
    <button class="close" data-close="alert"></button>
    <span>Jeżeli taki użytkownik istnieje to wysłaliśmy email z linkiem do zmiany hasła</span>
</div>
<div class="form-group <?php if($this->formElementErrors($form->get('email'))) echo "has-error has-feedback" ?>">
    <label class="control-label visible-ie8 visible-ie9"><?php echo $form->get('email')->getLabel(); ?></label>
    <div class="input-icon">
        <i class="fa fa-envelope"></i>
        <?php echo $this->formElement($form->get('email'));?>
        <?php if($this->formElementErrors($form->get('email'))) : ?>
            <span class="help-inline"><?php echo $this->formElementErrors($form->get('email')) ?></span>
        <?php endif; ?>
    </div>
</div>
<div class="form-actions">
    <button type="button" id="back-btn" class="btn"><i class="m-icon-swapleft"></i> Wstecz </button>
    <button id="passwordRecoverySubmitBtn" class="btn blue pull-right">Wyślij <i class="m-icon-swapright m-icon-white"></i>
    </button>
</div>
<?php echo $this->form()->closeTag($form); ?>