<?php
$form = $this->form;
$form->prepare();
echo $this->form()->openTag($form);
?>
<?php if($this->error) : ?>
    <div class="alert alert-danger display-show">
        <button class="close" data-close="alert"></button>
        <span><?php echo $this->error; ?></span>
    </div>
    <div class="form-actions">
        <button type="button" id="passwordResetBackBtn" class="btn"><i class="m-icon-swapleft"></i> Wstecz </button>
    </div>
<?php else : ?>
    <h3 class="form-title">Wprowadź nowe hasło</h3>
    <?php if($this->success) : ?>
        <div class="alert alert-success display-show">
            <button class="close" data-close="alert"></button>
            <span>Hasło zostało zmienione. Kliknij <a href="<?php echo $this->url('login'); ?>">tutaj</a> aby się zalogować</span>
        </div>
    <?php endif; ?>
    <div class="form-group <?php if($this->formElementErrors($form->get('password'))) echo "has-error has-feedback" ?>">
        <label class="control-label visible-ie8 visible-ie9"><?php echo $form->get('password')->getLabel(); ?></label>
        <div class="input-icon">
            <i class="fa fa-lock"></i>
            <?php echo $this->formElement($form->get('password'));?>
            <?php if($this->formElementErrors($form->get('password'))) : ?>
                <span class="help-inline"><?php echo $this->formElementErrors($form->get('password')) ?></span>
            <?php endif; ?>
        </div>
    </div>
    <div class="form-group <?php if($this->formElementErrors($form->get('rePassword'))) echo "has-error has-feedback" ?>">
        <label class="control-label visible-ie8 visible-ie9"><?php echo $form->get('rePassword')->getLabel(); ?></label>
        <div class="input-icon">
            <i class="fa fa-check"></i>
            <?php echo $this->formElement($form->get('rePassword'));?>
            <?php if($this->formElementErrors($form->get('rePassword'))) : ?>
                <span class="help-inline"><?php echo $this->formElementErrors($form->get('rePassword')) ?></span>
            <?php endif; ?>
        </div>
    </div>
    <div class="form-actions">
        <button type="button" id="passwordResetBackBtn" class="btn"><i class="m-icon-swapleft"></i> Wstecz </button>
        <button type="submit" class="btn blue pull-right">Wyślij <i class="m-icon-swapright m-icon-white"></i></button>
    </div>
<?php endif; ?>
<?php echo $this->form()->closeTag($form); ?>
